spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loan-service
    username: postgres
    password: 123
  liquibase:
    enabled: true
    changeLog: classpath:/db/changelog/liquibase.yaml
#    drop-first: true
  devtools:
    restart:
      enabled: true
